CREATE TABLE APP.CLIENT
(
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(25) NOT NULL UNIQUE,
    PASSWORD VARCHAR(20) NOT NULL,
    CREDIT DECIMAL(12,2) NOT NULL DEFAULT 0,
    CONSTRAINT CREDIT_CK CHECK (CREDIT >= 0)
);

CREATE TABLE APP.PRODUCT
(
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODE VARCHAR(15) NOT NULL UNIQUE,
    NAME VARCHAR(40) NOT NULL,
    CATEGORY VARCHAR(20) NOT NULL,
    PRICE DECIMAL(12,2) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    RATING DECIMAL(3,1) NOT NULL DEFAULT 0,
    CONSTRAINT PRICE_CK CHECK (PRICE > 0),
    CONSTRAINT PRODUCT_QUANTITY_CK CHECK (QUANTITY >= 0),
    CONSTRAINT RATING_CK CHECK (RATING >= 0 AND RATING <= 10)
);

CREATE TABLE APP.ORDERS
(
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT INTEGER NOT NULL,
    PRODUCT INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL,
    CONSTRAINT ORDER_QUANTITY_CK CHECK (QUANTITY > 0),
    CONSTRAINT CLIENT_FK FOREIGN KEY (CLIENT) REFERENCES APP.CLIENT(ID) ON DELETE CASCADE,
    CONSTRAINT PRODUCT_FK FOREIGN KEY (PRODUCT) REFERENCES APP.PRODUCT(ID) ON DELETE CASCADE
);

